
# All addresses choices are located in this file

# COUNTRY_CHOICES = [
#     ("AF", "Afghanistan"),
#     ("AX", "Aland Islands"),
#     ("AL", "Albania"),
#     ("DZ", "Algeria"),
#     ("AS", "American Samoa"),
#     ("AD", "Andorra"),
#     ("AO", "Angola"),
#     ("AI", "Anguilla"),
#     ("AQ", "Antarctica"),
#     ("AG", "Antigua and Barbuda"),
#     ("AR", "Argentina"),
#     ("AM", "Armenia"),
#     ("AW", "Aruba"),
#     ("AU", "Australia"),
#     ("AT", "Austria"),
#     ("AZ", "Azerbaijan"),
#     ("BS", "Bahamas"),
#     ("BH", "Bahrain"),
#     ("BD", "Bangladesh"),
#     ("BB", "Barbados"),
#     ("BE", "Belgium"),
#     ("BZ", "Belize"),
#     ("BJ", "Benin"),
#     ("BM", "Bermuda"),
#     ("BT", "Bhutan"),
#     ("BO", "Bolivia, Plurinational State of"),
#     ("BQ", "Bonaire, Sint Eustatius and Saba"),
#     ("BA", "Bosnia and Herzegovina"),
#     ("BW", "Botswana"),
#     ("BV", "Bouvet Island"),
#     ("BR", "Brazil"),
#     ("IO", "British Indian Ocean Territory"),
#     ("BN", "Brunei Darussalam"),
#     ("BG", "Bulgaria"),
#     ("BF", "Burkina Faso"),
#     ("BI", "Burundi"),
#     ("KH", "Cambodia"),
#     ("CM", "Cameroon"),
#     ("CA", "Canada"),
#     ("CV", "Cape Verde"),
#     ("KY", "Cayman Islands"),
#     ("CF", "Central African Republic"),
#     ("TD", "Chad"),
#     ("CL", "Chile"),
#     ("CN", "China"),
#     ("CX", "Christmas Island"),
#     ("CC", "Cocos (Keeling) Islands"),
#     ("CO", "Colombia"),
#     ("KM", "Comoros"),
#     ("CG", "Congo"),
#     ("CD", "Congo, The Democratic Republic of the"),
#     ("CK", "Cook Islands"),
#     ("CR", "Costa Rica"),
#     ("CI", "Côte d'Ivoire"),
#     ("HR", "Croatia"),
#     ("CU", "Cuba"),
#     ("CW", "Curaçao"),
#     ("CY", "Cyprus"),
#     ("CZ", "Czech Republic"),
#     ("DK", "Denmark"),
#     ("DJ", "Djibouti"),
#     ("DM", "Dominica"),
#     ("DO", "Dominican Republic"),
#     ("EC", "Ecuador"),
#     ("EG", "Egypt"),
#     ("SV", "El Salvador"),
#     ("GQ", "Equatorial Guinea"),
#     ("ER", "Eritrea"),
#     ("EE", "Estonia"),
#     ("ET", "Ethiopia"),
#     ("FK", "Falkland Islands (Malvinas)"),
#     ("FO", "Faroe Islands"),
#     ("FJ", "Fiji"),
#     ("FI", "Finland"),
#     ("FR", "France"),
#     ("GF", "French Guiana"),
#     ("PF", "French Polynesia"),
#     ("TF", "French Southern Territories"),
#     ("GA", "Gabon"),
#     ("GM", "Gambia"),
#     ("GE", "Georgia"),
#     ("DE", "Germany"),
#     ("GH", "Ghana"),
#     ("GI", "Gibraltar"),
#     ("GR", "Greece"),
#     ("GL", "Greenland"),
#     ("GD", "Grenada"),
#     ("GP", "Guadeloupe"),
#     ("GU", "Guam"),
#     ("GT", "Guatemala"),
#     ("GG", "Guernsey"),
#     ("GN", "Guinea"),
#     ("GW", "Guinea-Bissau"),
#     ("GY", "Guyana"),
#     ("HT", "Haiti"),
#     ("HM", "Heard Island and McDonald Islands"),
#     ("VA", "Holy See (Vatican City State)"),
#     ("HN", "Honduras"),
#     ("HK", "Hong Kong"),
#     ("HU", "Hungary"),
#     ("IS", "Iceland"),
#     ("IN", "India"),
#     ("ID", "Indonesia"),
#     ("IR", "Iran, Islamic Republic of"),
#     ("IQ", "Iraq"),
#     ("IE", "Ireland"),
#     ("IM", "Isle of Man"),
#     ("IL", "Israel"),
#     ("IT", "Italy"),
#     ("JM", "Jamaica"),
#     ("JP", "Japan"),
#     ("JE", "Jersey"),
#     ("JO", "Jordan"),
#     ("KZ", "Kazakhstan"),
#     ("KE", "Kenya"),
#     ("KI", "Kiribati"),
#     ("KP", "Korea, Democratic People's Republic of"),
#     ("KR", "Korea, Republic of"),
#     ("KW", "Kuwait"),
#     ("KG", "Kyrgyzstan"),
#     ("LA", "Lao People's Democratic Republic"),
#     ("LV", "Latvia"),
#     ("LB", "Lebanon"),
#     ("LS", "Lesotho"),
#     ("LR", "Liberia"),
#     ("LY", "Libya"),
#     ("LI", "Liechtenstein"),
#     ("LT", "Lithuania"),
#     ("LU", "Luxembourg"),
#     ("MO", "Macao"),
#     ("MK", "Macedonia, Republic of"),
#     ("MG", "Madagascar"),
#     ("MW", "Malawi"),
#     ("MY", "Malaysia"),
#     ("MV", "Maldives"),
#     ("ML", "Mali"),
#     ("MT", "Malta"),
#     ("MH", "Marshall Islands"),
#     ("MQ", "Martinique"),
#     ("MR", "Mauritania"),
#     ("MU", "Mauritius"),
#     ("YT", "Mayotte"),
#     ("MX", "Mexico"),
#     ("FM", "Micronesia, Federated States of"),
#     ("MD", "Moldova, Republic of"),
#     ("MC", "Monaco"),
#     ("MN", "Mongolia"),
#     ("ME", "Montenegro"),
#     ("MS", "Montserrat"),
#     ("MA", "Morocco"),
#     ("MZ", "Mozambique"),
#     ("MM", "Myanmar"),
#     ("NA", "Namibia"),
#     ("NR", "Nauru"),
#     ("NP", "Nepal"),
#     ("NL", "Netherlands"),
#     ("NC", "New Caledonia"),
#     ("NZ", "New Zealand"),
#     ("NI", "Nicaragua"),
#     ("NE", "Niger"),
#     ("NG", "Nigeria"),
#     ("NU", "Niue"),
#     ("NF", "Norfolk Island"),
#     ("MP", "Northern Mariana Islands"),
#     ("NO", "Norway"),
#     ("OM", "Oman"),
#     ("PK", "Pakistan"),
#     ("PW", "Palau"),
#     ("PS", "Palestinian Territory, Occupied"),
#     ("PA", "Panama"),
#     ("PG", "Papua New Guinea"),
#     ("PY", "Paraguay"),
#     ("PE", "Peru"),
#     ("PH", "Philippines"),
#     ("PN", "Pitcairn"),
#     ("PL", "Poland"),
#     ("PT", "Portugal"),
#     ("PR", "Puerto Rico"),
#     ("QA", "Qatar"),
#     ("RE", "Réunion"),
#     ("RO", "Romania"),
#     ("RW", "Rwanda"),
#     ("BL", "Saint Barthélemy"),
#     ("SH", "Saint Helena, Ascension and Tristan da Cunha"),
#     ("KN", "Saint Kitts and Nevis"),
#     ("LC", "Saint Lucia"),
#     ("MF", "Saint Martin (French part)"),
#     ("PM", "Saint Pierre and Miquelon"),
#     ("VC", "Saint Vincent and the Grenadines"),
#     ("WS", "Samoa"),
#     ("SM", "San Marino"),
#     ("ST", "Sao Tome and Principe"),
#     ("SA", "Saudi Arabia"),
#     ("SN", "Senegal"),
#     ("RS", "Serbia"),
#     ("SC", "Seychelles"),
#     ("SL", "Sierra Leone"),
#     ("SG", "Singapore"),
#     ("SX", "Sint Maarten (Dutch part)"),
#     ("SK", "Slovakia"),
#     ("SI", "Slovenia"),
#     ("SB", "Solomon Islands"),
#     ("SO", "Somalia"),
#     ("ZA", "South Africa"),
#     ("GS", "South Georgia and the South Sandwich Islands"),
#     ("ES", "Spain"),
#     ("LK", "Sri Lanka"),
#     ("SD", "Sudan"),
#     ("SR", "Suriname"),
#     ("SS", "South Sudan"),
#     ("SJ", "Svalbard and Jan Mayen"),
#     ("SZ", "Swaziland"),
#     ("SE", "Sweden"),
#     ("CH", "Switzerland"),
#     ("SY", "Syrian Arab Republic"),
#     ("TW", "Taiwan, Province of China"),
#     ("TJ", "Tajikistan"),
#     ("TZ", "Tanzania, United Republic of"),
#     ("TH", "Thailand"),
#     ("TL", "Timor-Leste"),
#     ("TG", "Togo"),
#     ("TK", "Tokelau"),
#     ("TO", "Tonga"),
#     ("TT", "Trinidad and Tobago"),
#     ("TN", "Tunisia"),
#     ("TR", "Turkey"),
#     ("TM", "Turkmenistan"),
#     ("TC", "Turks and Caicos Islands"),
#     ("TV", "Tuvalu"),
#     ("UG", "Uganda"),
#     ("UA", "Ukraine"),
#     ("AE", "United Arab Emirates"),
#     ("GB", "United Kingdom"),
#     ("US", "United States"),
#     ("UM", "United States Minor Outlying Islands"),
#     ("UY", "Uruguay"),
#     ("UZ", "Uzbekistan"),
#     ("VU", "Vanuatu"),
#     ("VE", "Venezuela, Bolivarian Republic of"),
#     ("VN", "Viet Nam"),
#     ("VG", "Virgin Islands, British"),
#     ("VI", "Virgin Islands, U.S."),
#     ("WF", "Wallis and Futuna"),
#     ("YE", "Yemen"),
#     ("ZM", "Zambia"),
#     ("ZW", "Zimbabwe"),
#]

COUNTRY_CHOICES = [
    ("Afghanistan", "Afghanistan"),
    ("Aland Islands", "Aland Islands"),
    ("Albania", "Albania"),
    ("Algeria", "Algeria"),
    ("American Samoa", "American Samoa"),
    ("Andorra", "Andorra"),
    ("Angola", "Angola"),
    ("Anguilla", "Anguilla"),
    ("Antarctica", "Antarctica"),
    ("Antigua and Barbuda", "Antigua and Barbuda"),
    ("Argentina", "Argentina"),
    ("Armenia", "Armenia"),
    ("Aruba", "Aruba"),
    ("Australia", "Australia"),
    ("Austria", "Austria"),
    ("Azerbaijan", "Azerbaijan"),
    ("Bahamas", "Bahamas"),
    ("Bahrain", "Bahrain"),
    ("Bangladesh", "Bangladesh"),
    ("Barbados", "Barbados"),
    ("Belgium", "Belgium"),
    ("Belize", "Belize"),
    ("Benin", "Benin"),
    ("Bermuda", "Bermuda"),
    ("Bhutan", "Bhutan"),
    ("Bolivia, Plurinational State of", "Bolivia, Plurinational State of"),
    ("Bonaire, Sint Eustatius and Saba", "Bonaire, Sint Eustatius and Saba"),
    ("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
    ("Botswana", "Botswana"),
    ("Bouvet Island", "Bouvet Island"),
    ("Brazil", "Brazil"),
    ("British Indian Ocean Territory", "British Indian Ocean Territory"),
    ("Brunei Darussalam", "Brunei Darussalam"),
    ("Bulgaria", "Bulgaria"),
    ("Burkina Faso", "Burkina Faso"),
    ("Burundi", "Burundi"),
    ("Cambodia", "Cambodia"),
    ("Cameroon", "Cameroon"),
    ("Canada", "Canada"),
    ("Cape Verde", "Cape Verde"),
    ("Cayman Islands", "Cayman Islands"),
    ("Central African Republic", "Central African Republic"),
    ("Chad", "Chad"),
    ("Chile", "Chile"),
    ("China", "China"),
    ("Christmas Island", "Christmas Island"),
    ("Cocos (Keeling) Islands", "Cocos (Keeling) Islands"),
    ("Colombia", "Colombia"),
    ("Comoros", "Comoros"),
    ("Congo", "Congo"),
    ("Congo, The Democratic Republic of the", "Congo, The Democratic Republic of the"),
    ("Cook Islands", "Cook Islands"),
    ("Costa Rica", "Costa Rica"),
    ("Côte d'Ivoire", "Côte d'Ivoire"),
    ("Croatia", "Croatia"),
    ("Cuba", "Cuba"),
    ("Curaçao", "Curaçao"),
    ("Cyprus", "Cyprus"),
    ("Czech Republic", "Czech Republic"),
    ("Denmark", "Denmark"),
    ("Djibouti", "Djibouti"),
    ("Dominica", "Dominica"),
    ("Dominican Republic", "Dominican Republic"),
    ("Ecuador", "Ecuador"),
    ("Egypt", "Egypt"),
    ("El Salvador", "El Salvador"),
    ("Equatorial Guinea", "Equatorial Guinea"),
    ("Eritrea", "Eritrea"),
    ("Estonia", "Estonia"),
    ("Ethiopia", "Ethiopia"),
    ("Falkland Islands (Malvinas)", "Falkland Islands (Malvinas)"),
    ("Faroe Islands", "Faroe Islands"),
    ("Fiji", "Fiji"),
    ("Finland", "Finland"),
    ("France", "France"),
    ("French Guiana", "French Guiana"),
    ("French Polynesia", "French Polynesia"),
    ("French Southern Territories", "French Southern Territories"),
    ("Gabon", "Gabon"),
    ("Gambia", "Gambia"),
    ("Georgia", "Georgia"),
    ("Germany", "Germany"),
    ("Ghana", "Ghana"),
    ("Gibraltar", "Gibraltar"),
    ("Greece", "Greece"),
    ("Greenland", "Greenland"),
    ("Grenada", "Grenada"),
    ("Guadeloupe", "Guadeloupe"),
    ("Guam", "Guam"),
    ("Guatemala", "Guatemala"),
    ("Guernsey", "Guernsey"),
    ("Guinea", "Guinea"),
    ("Guinea-Bissau", "Guinea-Bissau"),
    ("Guyana", "Guyana"),
    ("Haiti", "Haiti"),
    ("Heard Island and McDonald Islands", "Heard Island and McDonald Islands"),
    ("Holy See (Vatican City State)", "Holy See (Vatican City State)"),
    ("Honduras", "Honduras"),
    ("Hong Kong", "Hong Kong"),
    ("Hungary", "Hungary"),
    ("Iceland", "Iceland"),
    ("India", "India"),
    ("Indonesia", "Indonesia"),
    ("Iran, Islamic Republic of", "Iran, Islamic Republic of"),
    ("Iraq", "Iraq"),
    ("Ireland", "Ireland"),
    ("Isle of Man", "Isle of Man"),
    ("Israel", "Israel"),
    ("Italy", "Italy"),
    ("Jamaica", "Jamaica"),
    ("Japan", "Japan"),
    ("Jersey", "Jersey"),
    ("Jordan", "Jordan"),
    ("Kazakhstan", "Kazakhstan"),
    ("Kenya", "Kenya"),
    ("Kiribati", "Kiribati"),
    ("Korea, Democratic People's Republic of", "Korea, Democratic People's Republic of"),
    ("Korea, Republic of", "Korea, Republic of"),
    ("Kuwait", "Kuwait"),
    ("Kyrgyzstan", "Kyrgyzstan"),
    ("Lao People's Democratic Republic", "Lao People's Democratic Republic"),
    ("Latvia", "Latvia"),
    ("Lebanon", "Lebanon"),
    ("Lesotho", "Lesotho"),
    ("Liberia", "Liberia"),
    ("Libya", "Libya"),
    ("Liechtenstein", "Liechtenstein"),
    ("Lithuania", "Lithuania"),
    ("Luxembourg", "Luxembourg"),
    ("Macao", "Macao"),
    ("Macedonia, Republic of", "Macedonia, Republic of"),
    ("Madagascar", "Madagascar"),
    ("Malawi", "Malawi"),
    ("Malaysia", "Malaysia"),
    ("Maldives", "Maldives"),
    ("Mali", "Mali"),
    ("Malta", "Malta"),
    ("Marshall Islands", "Marshall Islands"),
    ("Martinique", "Martinique"),
    ("Mauritania", "Mauritania"),
    ("Mauritius", "Mauritius"),
    ("Mayotte", "Mayotte"),
    ("Mexico", "Mexico"),
    ("Micronesia, Federated States of", "Micronesia, Federated States of"),
    ("Moldova, Republic of", "Moldova, Republic of"),
    ("Monaco", "Monaco"),
    ("Mongolia", "Mongolia"),
    ("Montenegro", "Montenegro"),
    ("Montserrat", "Montserrat"),
    ("Morocco", "Morocco"),
    ("Mozambique", "Mozambique"),
    ("Myanmar", "Myanmar"),
    ("Namibia", "Namibia"),
    ("Nauru", "Nauru"),
    ("Nepal", "Nepal"),
    ("Netherlands", "Netherlands"),
    ("New Caledonia", "New Caledonia"),
    ("New Zealand", "New Zealand"),
    ("Nicaragua", "Nicaragua"),
    ("Niger", "Niger"),
    ("Nigeria", "Nigeria"),
    ("Niue", "Niue"),
    ("Norfolk Island", "Norfolk Island"),
    ("Northern Mariana Islands", "Northern Mariana Islands"),
    ("Norway", "Norway"),
    ("Oman", "Oman"),
    ("Pakistan", "Pakistan"),
    ("Palau", "Palau"),
    ("Palestinian Territory, Occupied", "Palestinian Territory, Occupied"),
    ("Panama", "Panama"),
    ("Papua New Guinea", "Papua New Guinea"),
    ("Paraguay", "Paraguay"),
    ("Peru", "Peru"),
    ("Philippines", "Philippines"),
    ("Pitcairn", "Pitcairn"),
    ("Poland", "Poland"),
    ("Portugal", "Portugal"),
    ("Puerto Rico", "Puerto Rico"),
    ("Qatar", "Qatar"),
    ("Réunion", "Réunion"),
    ("Romania", "Romania"),
    ("Rwanda", "Rwanda"),
    ("Saint Barthélemy", "Saint Barthélemy"),
    ("Saint Helena, Ascension and Tristan da Cunha", "Saint Helena, Ascension and Tristan da Cunha"),
    ("Saint Kitts and Nevis", "Saint Kitts and Nevis"),
    ("Saint Lucia", "Saint Lucia"),
    ("Saint Martin (French part)", "Saint Martin (French part)"),
    ("Saint Pierre and Miquelon", "Saint Pierre and Miquelon"),
    ("Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines"),
    ("Samoa", "Samoa"),
    ("San Marino", "San Marino"),
    ("Sao Tome and Principe", "Sao Tome and Principe"),
    ("Saudi Arabia", "Saudi Arabia"),
    ("Senegal", "Senegal"),
    ("Serbia", "Serbia"),
    ("Seychelles", "Seychelles"),
    ("Sierra Leone", "Sierra Leone"),
    ("Singapore", "Singapore"),
    ("Sint Maarten (Dutch part)", "Sint Maarten (Dutch part)"),
    ("Slovakia", "Slovakia"),
    ("Slovenia", "Slovenia"),
    ("Solomon Islands", "Solomon Islands"),
    ("Somalia", "Somalia"),
    ("South Africa", "South Africa"),
    ("South Georgia and the South Sandwich Islands", "South Georgia and the South Sandwich Islands"),
    ("Spain", "Spain"),
    ("Sri Lanka", "Sri Lanka"),
    ("Sudan", "Sudan"),
    ("Suriname", "Suriname"),
    ("South Sudan", "South Sudan"),
    ("Svalbard and Jan Mayen", "Svalbard and Jan Mayen"),
    ("Swaziland", "Swaziland"),
    ("Sweden", "Sweden"),
    ("Switzerland", "Switzerland"),
    ("Syrian Arab Republic", "Syrian Arab Republic"),
    ("Taiwan, Province of China", "Taiwan, Province of China"),
    ("Tajikistan", "Tajikistan"),
    ("Tanzania, United Republic of", "Tanzania, United Republic of"),
    ("Thailand", "Thailand"),
    ("Timor-Leste", "Timor-Leste"),
    ("Togo", "Togo"),
    ("Tokelau", "Tokelau"),
    ("Tonga", "Tonga"),
    ("Trinidad and Tobago", "Trinidad and Tobago"),
    ("Tunisia", "Tunisia"),
    ("Turkey", "Turkey"),
    ("Turkmenistan", "Turkmenistan"),
    ("Turks and Caicos Islands", "Turks and Caicos Islands"),
    ("Tuvalu", "Tuvalu"),
    ("Uganda", "Uganda"),
    ("Ukraine", "Ukraine"),
    ("United Arab Emirates", "United Arab Emirates"),
    ("United Kingdom", "United Kingdom"),
    ("United States", "United States"),
    ("United States Minor Outlying Islands", "United States Minor Outlying Islands"),
    ("Uruguay", "Uruguay"),
    ("Uzbekistan", "Uzbekistan"),
    ("Vanuatu", "Vanuatu"),
    ("Venezuela, Bolivarian Republic of", "Venezuela, Bolivarian Republic of"),
    ("Viet Nam", "Viet Nam"),
    ("Virgin Islands, British", "Virgin Islands, British"),
    ("Virgin Islands, U.S.", "Virgin Islands, U.S."),
    ("Wallis and Futuna", "Wallis and Futuna"),
    ("Yemen", "Yemen"),
    ("Zambia", "Zambia"),
    ("Zimbabwe", "Zimbabwe"),
]