# Generated by Django 4.1.6 on 2023-02-01 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_promotion_remove_productitem_product_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(99.9)]),
        ),
    ]
