# Generated by Django 4.1.6 on 2023-02-02 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_product_description_alter_productitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
