# Generated by Django 4.1.6 on 2023-02-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
