# Generated by Django 4.1.6 on 2023-02-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_product_created_productitem_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
