# Generated by Django 4.1.6 on 2023-02-03 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_discount_is_active_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
